server:
  port: 9004

spring:
  application:
    name: LIBRARY-SERVICE
  zipkin:
    base-url: http://localhost:9411/

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
eureka:
  client:
    fetch-registry: true